name: Tests
on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          architecture: x64
          cache: pip
          cache-dependency-path: requirements/requirements_tests.txt
          python-version: "3.11"
      - name: Install dependencies
        run: "python -m pip install --upgrade pip setuptools

          pip install --requirement requirements/requirements_tests.txt

          # Download models and data files

          python utils/wl_download_ci.py

          python utils/wl_download_modern_botok.py

          python utils/wl_download_pkuseg.py

          "
        continue-on-error: true
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Run Tests
        run: "# Fix PyQt

          export QT_QPA_PLATFORM=offscreen


          # Run some tests separately to reduce memory usage

          pytest tests/tests_nlp/test_dependency_parsing.py

          pytest tests/tests_nlp/test_lemmatization.py

          pytest tests/tests_nlp/test_matching.py

          pytest tests/tests_nlp/test_nlp_utils.py

          pytest tests/tests_nlp/test_pos_tagging.py

          pytest tests/tests_nlp/test_sentence_tokenization.py

          pytest tests/tests_nlp/test_sentiment_analysis.py

          pytest tests/tests_nlp/test_stop_word_lists.py

          pytest tests/tests_nlp/test_syl_tokenization.py

          pytest tests/tests_nlp/test_texts.py

          pytest tests/tests_nlp/test_token_processing.py

          pytest tests/tests_nlp/test_word_detokenization.py

          pytest tests/tests_nlp/test_word_tokenization.py


          pytest tests/test_colligation_extractor.py

          pytest tests/test_collocation_extractor.py

          pytest tests/test_concordancer.py

          pytest tests/test_concordancer_parallel.py

          pytest tests/test_dependency_parser.py

          pytest tests/test_keyword_extractor.py

          pytest tests/test_main.py

          pytest tests/test_ngram_generator.py

          pytest tests/test_profiler.py

          pytest tests/test_wordlist_generator.py


          # Exclude tests_settings on Linux

          pytest --ignore=tests/tests_nlp --ignore=tests/test_colligation_extractor.py
          --ignore=tests/test_collocation_extractor.py --ignore=tests/test_concordancer.py
          --ignore=tests/test_concordancer_parallel.py --ignore=tests/test_dependency_parser.py
          --ignore=tests/test_keyword_extractor.py --ignore=tests/test_main.py --ignore=tests/test_ngram_generator.py
          --ignore=tests/test_profiler.py --ignore=tests/test_wordlist_generator.py
          --ignore=tests/tests_nlp --ignore=tests/tests_settings

          "
        continue-on-error: true
      - id: measurement-6
        name: Record Measurement After Run Tests
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Run Tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
